In [2]:
 # Import Libraries

import numpy as np
import pandas as pd

In [3]:
df = pd.read_csv("Car_Price_Data.csv")
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 892 entries, 0 to 891
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   name        892 non-null    str
 1   company     892 non-null    str
 2   year        892 non-null    str
 3   Price       892 non-null    str
 4   kms_driven  840 non-null    str
 5   fuel_type   837 non-null    str
dtypes: str(6)
memory usage: 41.9 KB

In [4]:
 # Clean Price Column

df['Price'].unique().tolist()
df = df[df['Price'] != 'Ask For Price']
df['Price'] = df['Price'].str.replace(',', '')
df['Price'] = df['Price'].astype(int)

In [5]:
df['Price'].unique().tolist()

[80000,
 425000,
 325000,
 575000,
 175000,
 190000,
 830000,
 250000,
 182000,
 315000,
 415000,
 320000,
 1000000,
 500000,
 350000,
 160000,
 310000,
 75000,
 100000,
 290000,
 95000,
 180000,
 385000,
 105000,
 650000,
 689999,
 448000,
 549000,
 501000,
 489999,
 280000,
 349999,
 284999,
 345000,
 499999,
 235000,
 249999,
 1475000,
 395000,
 220000,
 170000,
 85000,
 200000,
 570000,
 110000,
 448999,
 1891111,
 159500,
 344999,
 449999,
 865000,
 699000,
 375000,
 224999,
 1200000,
 195000,
 351000,
 240000,
 90000,
 155000,
 600000,
 189500,
 210000,
 390000,
 135000,
 1600000,
 701000,
 265000,
 525000,
 372000,
 635000,
 550000,
 485000,
 329500,
 251111,
 569999,
 69999,
 299999,
 399999,
 450000,
 270000,
 158400,
 179000,
 125000,
 299000,
 150000,
 275000,
 285000,
 340000,
 70000,
 289999,
 849999,
 749999,
 274999,
 984999,
 599999,
 244999,
 474999,
 245000,
 169500,
 370000,
 168000,
 145000,
 98500,
 209000,
 185000,
 900000,
 699999,
 199999,
 544999,
 199000,
 540000,
 49000,
 700000,
 55000,
 895000,
 355000,
 565000,
 365000,
 40000,
 400000,
 330000,
 580000,
 379000,
 219000,
 519000,
 730000,
 2000000,
 2100000,
 1400000,
 311000,
 855000,
 535000,
 178000,
 300000,
 255000,
 549999,
 380000,
 57000,
 410000,
 225000,
 120000,
 59000,
 599000,
 675000,
 72500,
 610000,
 230000,
 520000,
 524999,
 424999,
 644999,
 584999,
 799999,
 444999,
 649999,
 944999,
 574999,
 374999,
 130000,
 401000,
 1350000,
 174999,
 239999,
 99999,
 324999,
 1074999,
 1130000,
 149000,
 770000,
 30000,
 335000,
 399000,
 65000,
 169999,
 165000,
 560000,
 950000,
 715000,
 45000,
 940000,
 155555,
 1500000,
 495000,
 800000,
 1299000,
 530000,
 1499000,
 32000,
 405000,
 760000,
 750000,
 419000,
 140000,
 1540000,
 123000,
 498000,
 480000,
 488000,
 1525000,
 548900,
 725000,
 99000,
 52000,
 2800000,
 499000,
 381000,
 278000,
 690000,
 260000,
 90001,
 115000,
 1599000,
 159000,
 51999,
 215000,
 35000,
 1150000,
 269000,
 60000,
 430000,
 8500003,
 401919,
 490000,
 424000,
 205000,
 549900,
 371500,
 435000,
 189700,
 389700,
 360000,
 295000,
 114990,
 1065000,
 470000,
 48000,
 188000,
 465000,
 179999,
 2190000,
 2390000,
 1075000,
 475000,
 1025000,
 615000,
 1900000,
 1490000,
 1510000,
 1850000,
 790000,
 1725000,
 1225000,
 68000,
 970000,
 3100000,
 899000,
 88000,
 53000,
 568500,
 71000,
 590000,
 795000,
 42000,
 189000,
 162000,
 35999,
 2900000,
 39999,
 50500,
 510000,
 860000,
 500001]

In [6]:
df.info()

<class 'pandas.DataFrame'>
Index: 857 entries, 0 to 891
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   name        857 non-null    str
 1   company     857 non-null    str
 2   year        857 non-null    str
 3   Price       857 non-null    int64
 4   kms_driven  819 non-null    str
 5   fuel_type   816 non-null    str
dtypes: int64(1), str(5)
memory usage: 46.9 KB

In [7]:
 # Clean Year Column

df['year'].unique().tolist()
df = df[df['year'].str.isnumeric()]
df['year'] = df['year'].astype(int)

In [8]:
df['year'].unique().tolist()

[2007,
 2006,
 2014,
 2012,
 2013,
 2016,
 2015,
 2010,
 2017,
 2008,
 2018,
 2011,
 2019,
 2009,
 2005,
 2000,
 2003,
 2004,
 1995,
 2002,
 2001]

In [9]:
 # Clean kms column

df['kms_driven'].unique().tolist()
df = df.dropna(subset=['kms_driven'])
df['kms_driven'] = df['kms_driven'].str.replace(' kms', '')
df['kms_driven'] = df['kms_driven'].str.replace(',', '')
df = df[df['kms_driven'].str.isnumeric()]
df['kms_driven'] = df['kms_driven'].astype(int)

In [10]:
df['kms_driven'].unique().tolist()

[45000,
 40,
 28000,
 36000,
 41000,
 25000,
 24530,
 60000,
 30000,
 32000,
 48660,
 4000,
 16934,
 43000,
 35550,
 39522,
 39000,
 55000,
 72000,
 15975,
 70000,
 23452,
 35522,
 48508,
 15487,
 82000,
 20000,
 68000,
 38000,
 27000,
 33000,
 46000,
 16000,
 47000,
 35000,
 30874,
 15000,
 29685,
 130000,
 19000,
 54000,
 13000,
 38200,
 22000,
 50000,
 13500,
 3600,
 45863,
 60500,
 12500,
 18000,
 13349,
 29000,
 44000,
 42000,
 14000,
 49000,
 36200,
 51000,
 104000,
 33333,
 33600,
 5600,
 7500,
 26000,
 24330,
 65480,
 200000,
 59000,
 99000,
 2800,
 21000,
 11000,
 66000,
 3000,
 7000,
 38500,
 37200,
 43200,
 24800,
 45872,
 40000,
 11400,
 97200,
 52000,
 31000,
 175430,
 37000,
 65000,
 3350,
 75000,
 62000,
 73000,
 2200,
 54870,
 34580,
 97000,
 60,
 80200,
 3200,
 0,
 5000,
 588,
 71200,
 175400,
 9300,
 56758,
 10000,
 56450,
 56000,
 32700,
 9000,
 73,
 160000,
 58559,
 57000,
 170000,
 80000,
 6821,
 23000,
 34000,
 1800,
 400000,
 48000,
 90000,
 12000,
 69900,
 166000,
 122,
 36469,
 7800,
 24695,
 15141,
 59910,
 100000,
 4500,
 129000,
 300,
 131000,
 111111,
 59466,
 25500,
 44005,
 2110,
 43222,
 100200,
 65,
 140000,
 103553,
 58000,
 120000,
 49800,
 100,
 81876,
 6020,
 55700,
 18500,
 53000,
 35500,
 22134,
 1000,
 8500,
 87000,
 6000,
 8000,
 55800,
 56400,
 72160,
 11500,
 133000,
 2000,
 88000,
 65422,
 117000,
 150000,
 10750,
 6800,
 9800,
 57923,
 30201,
 6200,
 37518,
 24652,
 383,
 95000,
 3528,
 52500,
 47900,
 52800,
 195000,
 48008,
 48247,
 9400,
 64000,
 2137,
 10544,
 147000,
 90001,
 48006,
 74000,
 85000,
 29500,
 39700,
 67000,
 19336,
 60105,
 45933,
 102563,
 28600,
 41800,
 116000,
 42590,
 7400,
 54500,
 76000,
 11523,
 38600,
 95500,
 37458,
 85960,
 12516,
 30600,
 2550,
 62500,
 69000,
 28400,
 68485,
 3500,
 85455,
 63000,
 1600,
 77000,
 26500,
 2875,
 13900,
 1500,
 2450,
 1625,
 33400,
 60123,
 137495,
 91200,
 146000,
 100800,
 2100,
 2500,
 132000]

In [13]:
 # Clean Fuel Column

df['fuel_type'].unique().tolist()
df = df.dropna(subset=["fuel_type"])
df.info()

<class 'pandas.DataFrame'>
Index: 816 entries, 0 to 889
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   name        816 non-null    str
 1   company     816 non-null    str
 2   year        816 non-null    int64
 3   Price       816 non-null    int64
 4   kms_driven  816 non-null    int64
 5   fuel_type   816 non-null    str
dtypes: int64(3), str(3)
memory usage: 44.6 KB

In [14]:
df['fuel_type'].unique().tolist()

['Petrol', 'Diesel', 'LPG']

In [15]:
# STEP 6: Remove Whitespace and Text Anomalies

df["name"] = df["name"].str.strip()
df["company"] = df["company"].str.strip()
df["fuel_type"] = df["fuel_type"].str.strip()

In [16]:
df

,name,company,year,Price,kms_driven,fuel_type
0,Hyundai Santro Xing XO eRLX Euro III,Hyundai,2007,80000,45000,Petrol
1,Mahindra Jeep CL550 MDI,Mahindra,2006,425000,40,Diesel
3,Hyundai Grand i10 Magna 1.2 Kappa VTVT,Hyundai,2014,325000,28000,Petrol
4,Ford EcoSport Titanium 1.5L TDCi,Ford,2014,575000,36000,Diesel
6,Ford Figo,Ford,2012,175000,41000,Diesel
...,...,...,...,...,...,...
883,Maruti Suzuki Ritz VXI ABS,Maruti,2011,270000,50000,Petrol
885,Tata Indica V2 DLE BS III,Tata,2009,110000,30000,Diesel
886,Toyota Corolla Altis,Toyota,2009,300000,132000,Petrol
888,Tata Zest XM Diesel,Tata,2018,260000,27000,Diesel
889,Mahindra Quanto C8,Mahindra,2013,390000,40000,Diesel

In [17]:
# STEP 7: Reset the Index and Save Clean Data

df = df.reset_index(drop=True)

In [18]:
df

,name,company,year,Price,kms_driven,fuel_type
0,Hyundai Santro Xing XO eRLX Euro III,Hyundai,2007,80000,45000,Petrol
1,Mahindra Jeep CL550 MDI,Mahindra,2006,425000,40,Diesel
2,Hyundai Grand i10 Magna 1.2 Kappa VTVT,Hyundai,2014,325000,28000,Petrol
3,Ford EcoSport Titanium 1.5L TDCi,Ford,2014,575000,36000,Diesel
4,Ford Figo,Ford,2012,175000,41000,Diesel
...,...,...,...,...,...,...
811,Maruti Suzuki Ritz VXI ABS,Maruti,2011,270000,50000,Petrol
812,Tata Indica V2 DLE BS III,Tata,2009,110000,30000,Diesel
813,Toyota Corolla Altis,Toyota,2009,300000,132000,Petrol
814,Tata Zest XM Diesel,Tata,2018,260000,27000,Diesel
815,Mahindra Quanto C8,Mahindra,2013,390000,40000,Diesel

In [19]:
df.duplicated().value_counts()

False    724
True      92
Name: count, dtype: int64

In [20]:
df = df.drop_duplicates()

In [21]:
df.info()

<class 'pandas.DataFrame'>
Index: 724 entries, 0 to 815
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   name        724 non-null    str
 1   company     724 non-null    str
 2   year        724 non-null    int64
 3   Price       724 non-null    int64
 4   kms_driven  724 non-null    int64
 5   fuel_type   724 non-null    str
dtypes: int64(3), str(3)
memory usage: 39.6 KB

In [22]:
df.duplicated().value_counts()

False    724
Name: count, dtype: int64

In [23]:
for i in df.index:
    name = df.loc[i,"name"]
    company = df.loc[i,"company"]
    name = name.replace(company + " ","")
    name = ' '.join(name.split()[:3])
    df.loc[i,"name"] = name

In [24]:
df

                       name   company  year   Price  kms_driven fuel_type
0            Santro Xing XO   Hyundai  2007   80000       45000    Petrol
1            Jeep CL550 MDI  Mahindra  2006  425000          40    Diesel
2           Grand i10 Magna   Hyundai  2014  325000       28000    Petrol
3    EcoSport Titanium 1.5L      Ford  2014  575000       36000    Diesel
4                      Figo      Ford  2012  175000       41000    Diesel
..                      ...       ...   ...     ...         ...       ...
811         Suzuki Ritz VXI    Maruti  2011  270000       50000    Petrol
812           Indica V2 DLE      Tata  2009  110000       30000    Diesel
813           Corolla Altis    Toyota  2009  300000      132000    Petrol
814          Zest XM Diesel      Tata  2018  260000       27000    Diesel
815               Quanto C8  Mahindra  2013  390000       40000    Diesel

[724 rows x 6 columns]

In [26]:
# Save the polished data to a new CSV file
df.to_csv("Cleaned_Car_Price_Data.csv", index=False)

In [27]:
print("--- Post-Cleaning Data Info ---")
print(df.info())
print("\nSuccess! The clean dataset has been saved as 'Cleaned_Car_Price_Data.csv'.")

--- Post-Cleaning Data Info ---
<class 'pandas.DataFrame'>
Index: 724 entries, 0 to 815
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   name        724 non-null    str
 1   company     724 non-null    str
 2   year        724 non-null    int64
 3   Price       724 non-null    int64
 4   kms_driven  724 non-null    int64
 5   fuel_type   724 non-null    str
dtypes: int64(3), str(3)
memory usage: 55.8 KB
None

Success! The clean dataset has been saved as 'Cleaned_Car_Price_Data.csv'.